version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - ./bank:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: laravel-db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
        volumes:
            - ./db.sql:/docker-entrypoint-initdb.d/db