version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bank
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db.sql:/docker-entrypoint-initdb.d/db.sql
